config/routes.rb
Rails.application.routes.draw do
  get 'points/index'
  get 'points/import'

  resources :points do
  	collection { post :import}
  end

  root to: "points#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  require 'csv'
	#validates :user, :steps, :distance, :exercise, :sleep, :calories, presence: true

	def self.import(file)
		CSV.foreach(file.path, {encoding: "UTF-8", col_sep: ";", headers: true, header_converters: :symbol, converters: :all}) do |row|
			if Point.exists?(name: row[:name])
				puts 'this point already exists'
			else
				Point.create! row.to_hash
			end
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def redirect(url, text)
  	redirect_to url, notice: text
  end
  
  def index
    @points = Point.all
  end

  def import
    if params[:file]
  		Point.import(params[:file])
  		redirect(root_url, "Activity Data imported!")	
  	else
  		redirect(root_url, "Please upload a CSV file")
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmvImportCsv</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/points/import.html.erb
<h1>Points#import</h1>
<p>Find me in app/views/points/import.html.erb</p>

app/views/points/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
    <th>Id</th>
		<th>Name</th>
		<th>Short Description</th>
    <th>Description</th>
    <th>Region</th>
    <th>City</th>
    <th>Street</th>
		<th>Street number</th>
    <th>Province</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Category</th>
	</thead>
	<tbody>
		<% @points.each do |point| %>
      <tr>
        <td><%= point.id%></td>
				<td><%= point.name %></td>
				<td><%= point.short_description %></td>
        <td><%= point.description %></td>
        <td><%= point.region%></td>
				<td><%= point.city %></td>
				<td><%= point.street %></td>
				<td><%= point.street_number %></td>
				<td><%= point.province %></td>
				<td><%= point.zipcode %></td>
				<td><%= point.country %></td>
				<td><%= point.latitude %></td>
				<td><%= point.longitude %></td>
				<td><%= point.category %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<div>
	<h4> Import! </h4>
		<%= form_tag import_points_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "Import CSV" %>
		<% end %> 
</div>